// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kol2b.Models;

namespace kol2b.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20220614073218_test1")]
    partial class test1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kol2b.Models.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("IdMusicLabel")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAlbum");

                    b.HasIndex("IdMusicLabel");

                    b.ToTable("Album");

                    b.HasData(
                        new
                        {
                            IdAlbum = 1,
                            AlbumName = "name1",
                            IdMusicLabel = 1,
                            PublishDate = new DateTime(2022, 6, 14, 9, 32, 17, 414, DateTimeKind.Local).AddTicks(3415)
                        },
                        new
                        {
                            IdAlbum = 2,
                            AlbumName = "name2",
                            IdMusicLabel = 2,
                            PublishDate = new DateTime(2022, 6, 14, 9, 32, 17, 419, DateTimeKind.Local).AddTicks(4922)
                        },
                        new
                        {
                            IdAlbum = 3,
                            AlbumName = "name3",
                            IdMusicLabel = 2,
                            PublishDate = new DateTime(2022, 6, 14, 9, 32, 17, 419, DateTimeKind.Local).AddTicks(4990)
                        });
                });

            modelBuilder.Entity("kol2b.Models.MusicLabel", b =>
                {
                    b.Property<int>("IdMusicLabel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdMusicLabel");

                    b.ToTable("MusicLabel");

                    b.HasData(
                        new
                        {
                            IdMusicLabel = 1,
                            Name = "Moya"
                        },
                        new
                        {
                            IdMusicLabel = 2,
                            Name = "Twoya"
                        });
                });

            modelBuilder.Entity("kol2b.Models.Musician", b =>
                {
                    b.Property<int>("IdMusician")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdMusician");

                    b.ToTable("Musician");

                    b.HasData(
                        new
                        {
                            IdMusician = 1,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            Nickname = "Lil Drzoni"
                        },
                        new
                        {
                            IdMusician = 2,
                            FirstName = "Piotr",
                            LastName = "Nowag",
                            Nickname = "Big papi"
                        });
                });

            modelBuilder.Entity("kol2b.Models.MusicianTrack", b =>
                {
                    b.Property<int>("IdMusician")
                        .HasColumnType("int");

                    b.Property<int>("IdTrack")
                        .HasColumnType("int");

                    b.HasKey("IdMusician", "IdTrack");

                    b.HasIndex("IdTrack");

                    b.ToTable("Musican_Track");

                    b.HasData(
                        new
                        {
                            IdMusician = 1,
                            IdTrack = 1
                        },
                        new
                        {
                            IdMusician = 2,
                            IdTrack = 2
                        });
                });

            modelBuilder.Entity("kol2b.Models.Track", b =>
                {
                    b.Property<int>("IdTrack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<int>("IdMusicAlbum")
                        .HasColumnType("int");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdTrack");

                    b.HasIndex("IdMusicAlbum");

                    b.ToTable("Track");

                    b.HasData(
                        new
                        {
                            IdTrack = 1,
                            Duration = 4f,
                            IdMusicAlbum = 1,
                            TrackName = "song1"
                        },
                        new
                        {
                            IdTrack = 2,
                            Duration = 3f,
                            IdMusicAlbum = 1,
                            TrackName = "song2"
                        },
                        new
                        {
                            IdTrack = 3,
                            Duration = 6f,
                            IdMusicAlbum = 2,
                            TrackName = "song3"
                        });
                });

            modelBuilder.Entity("kol2b.Models.Album", b =>
                {
                    b.HasOne("kol2b.Models.MusicLabel", "MusicLabel")
                        .WithMany("Album")
                        .HasForeignKey("IdMusicLabel")
                        .IsRequired();

                    b.Navigation("MusicLabel");
                });

            modelBuilder.Entity("kol2b.Models.MusicianTrack", b =>
                {
                    b.HasOne("kol2b.Models.Musician", "Musician")
                        .WithMany("MusicanTrack")
                        .HasForeignKey("IdMusician")
                        .IsRequired();

                    b.HasOne("kol2b.Models.Track", "Track")
                        .WithMany("MusicianTrack")
                        .HasForeignKey("IdTrack")
                        .IsRequired();

                    b.Navigation("Musician");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("kol2b.Models.Track", b =>
                {
                    b.HasOne("kol2b.Models.Album", "Album")
                        .WithMany("Track")
                        .HasForeignKey("IdMusicAlbum");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("kol2b.Models.Album", b =>
                {
                    b.Navigation("Track");
                });

            modelBuilder.Entity("kol2b.Models.MusicLabel", b =>
                {
                    b.Navigation("Album");
                });

            modelBuilder.Entity("kol2b.Models.Musician", b =>
                {
                    b.Navigation("MusicanTrack");
                });

            modelBuilder.Entity("kol2b.Models.Track", b =>
                {
                    b.Navigation("MusicianTrack");
                });
#pragma warning restore 612, 618
        }
    }
}
